_extends: .github

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: resume

  # A short description of the repository that will show up on GitHub
  description: Personal resume

  # A URL with more information about the repository
  homepage: https://resume.bje.co/

  # A comma-separated list of topics to set on the repository
  topics: resume, react, nextjs, linkedin

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

branches:
  - name: main
