name: Setup
description: Enable corepack and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6.2.0
      with:
        node-version-file: .nvmrc
    - run: corepack enable
      shell: bash
    - name: Get pnpm store directory
      id: pnpm-store-dir
      run: echo "dir=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v5.0.3
      with:
        path: ${{ steps.pnpm-store-dir.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - run: pnpm install --frozen-lockfile
      shell: bash
